AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Document Query System with LLM-based RAG

Globals:
  Function:
    Timeout: 900
    MemorySize: 3000
    Tracing: Active

Parameters:
  LangsmithTracing:
    Type: String
  LangsmithApiKey:
    Type: String
  LangsmithProject:
    Type: String
  GroqApiKey:
    Type: String
  PineconeApiKey:
    Type: String
  PineconeIndex:
    Type: String
  CohereApiKey:
    Type: String
  BM25EncoderFile:
    Type: String
  S3BucketName:
    Type: String
  RagDeployRole:
    Type: String

Resources:
  RagServicesBackend:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Role: !Ref RagDeployRole
      Environment:
        Variables:
          LANGSMITH_TRACING: !Ref LangsmithTracing
          LANGSMITH_API_KEY: !Ref LangsmithApiKey
          LANGSMITH_PROJECT: !Ref LangsmithProject
          GROQ_API_KEY: !Ref GroqApiKey
          PINECONE_API_KEY: !Ref PineconeApiKey
          PINECONE_INDEX: !Ref PineconeIndex
          COHERE_API_KEY: !Ref CohereApiKey
          BM25_ENCODER_FILE: !Ref BM25EncoderFile
          S3_BUCKET_NAME: !Ref S3BucketName
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: production_rag
