name: Deploy RAG

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GIT_ACTION_ROLE }}
          aws-region: us-east-1

      - name: Install SAM
        run: |
          pip install aws-sam-cli

      - name: Build SAM
        run: sam build --use-container -t template.yml

      - name: Deploy SAM
        run: |
          sam deploy \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset \
          --capabilities CAPABILITY_IAM \
          --config-file samconfig.toml \
          --parameter-overrides \
          ParameterKey=LangsmithTracing,ParameterValue=${{ secrets.LANGSMITH_TRACING }} \
          ParameterKey=LangsmithApiKey,ParameterValue=${{ secrets.LANGSMITH_API_KEY }} \
          ParameterKey=LangsmithProject,ParameterValue=${{ secrets.LANGSMITH_PROJECT }} \
          ParameterKey=GroqApiKey,ParameterValue=${{ secrets.GROQ_API_KEY }} \
          ParameterKey=PineconeApiKey,ParameterValue=${{ secrets.PINECONE_API_KEY }} \
          ParameterKey=PineconeIndex,ParameterValue=${{ secrets.PINECONE_INDEX }} \
          ParameterKey=CohereApiKey,ParameterValue=${{ secrets.COHERE_API_KEY }} \
          ParameterKey=BM25EncoderFile,ParameterValue=${{ secrets.BM25_ENCODER_FILE }} \
          ParameterKey=S3BucketName,ParameterValue=${{ secrets.S3_BUCKET_NAME }} \
          ParameterKey=RagDeployRole,ParameterValue=${{ secrets.RAG_DEPLOY_ROLE }} \