name: Deploy RAG

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::815210276228:role/Git-Action
          aws-region: us-east-1

      - name: Install SAM
        run: |
          pip install aws-sam-cli

      - name: Build SAM
        run: sam build --use-container -t template-dev.yml

      - name: Deploy SAM
        run: |
          sam deploy \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset \
          --stack-name doc-query-rag \
          --parameter-overrides \
          LangsmithTracing=${{ secrets.LANGSMITH_TRACING }} \
          LangsmithApiKey=${{ secrets.LANGSMITH_API_KEY }} \
          LangsmithProject=${{ secrets.LANGSMITH_PROJECT }} \
          GroqApiKey=${{ secrets.GROQ_API_KEY }} \
          PineconeApiKey=${{ secrets.PINECONE_API_KEY }} \
          PineconeIndex=${{ secrets.PINECONE_INDEX }} \
          CohereApiKey=${{ secrets.COHERE_API_KEY }} \
          BM25EncoderFile=${{ secrets.BM25_ENCODER_FILE }} \
          S3BucketName=${{ secrets.S3_BUCKET_NAME }} \
          AwsAccessKeyId=${{ secrets.AWS_ACCESS_KEY_ID }} \
          AwsSecretAccessKey=${{ secrets.AWS_SECRET_ACCESS_KEY }}